// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnm2FmYvDREIKHYKYdHR0EvcNoZzWDNcY',
    appId: '1:712444672674:web:eebde9b4d3bd5e17ab75fb',
    messagingSenderId: '712444672674',
    projectId: 'food-528f6',
    authDomain: 'food-528f6.firebaseapp.com',
    storageBucket: 'food-528f6.firebasestorage.app',
    measurementId: 'G-SQ4Q2K9PLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7N2uS0rQk17ZF3fqv8f_730XJs24XQKA',
    appId: '1:712444672674:android:773cf9e3413c4bdfab75fb',
    messagingSenderId: '712444672674',
    projectId: 'food-528f6',
    storageBucket: 'food-528f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-4AYX_5_TVelakXWpKX71A8G1JPJBfHI',
    appId: '1:712444672674:ios:416e4c7888ef211bab75fb',
    messagingSenderId: '712444672674',
    projectId: 'food-528f6',
    storageBucket: 'food-528f6.firebasestorage.app',
    iosBundleId: 'com.example.foodOrderingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-4AYX_5_TVelakXWpKX71A8G1JPJBfHI',
    appId: '1:712444672674:ios:416e4c7888ef211bab75fb',
    messagingSenderId: '712444672674',
    projectId: 'food-528f6',
    storageBucket: 'food-528f6.firebasestorage.app',
    iosBundleId: 'com.example.foodOrderingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnm2FmYvDREIKHYKYdHR0EvcNoZzWDNcY',
    appId: '1:712444672674:web:42fa074bf4987a8bab75fb',
    messagingSenderId: '712444672674',
    projectId: 'food-528f6',
    authDomain: 'food-528f6.firebaseapp.com',
    storageBucket: 'food-528f6.firebasestorage.app',
    measurementId: 'G-Q3STD8BK9N',
  );
}
